version: '3.1'

services:
  db:
    image: postgres:latest
    platform: linux/arm64
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=appdata
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=password

  api:
    build:
      context: api
      dockerfile: Dockerfile.m1
    entrypoint: ["./entrypoint.sh"]
    ports:
      - "8000:8000"
    volumes:
      - ./api:/code
    environment:
      - POSTGRES_DB=appdata
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=password
      - LOG_LOCATION=/var/log/api.log
    depends_on:
      - db
    logging:
      options:
        max-size: "10m"
        max-file: "10"
        compress: "true"

volumes:
  db-data: