# Generated by Django 4.2.13 on 2024-05-18 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teacher_student_course_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='school',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='school_administrator', to='core.school'),
        ),
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='school_course', to='core.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='school_student', to='core.school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='school_teacher', to='core.school'),
        ),
    ]
