# Generated by Django 4.2.13 on 2024-05-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teacher_student_course_administrator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'school')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'school')},
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('name', 'school')},
        ),
    ]
